### ISSUE TITLE
Unknown Interaction

### ISSUE THREAD

**Issue by dustinlacewell** [rossimo/retrobot#7]
```
DiscordAPIError[10062]: Unknown interaction
    at SequentialHandler.runRequest (C:\Users\dustin\shared\discord\retrobot\node_modules\@discordjs\rest\src\lib\handlers\SequentialHandler.ts:293:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.queueRequest (C:\Users\dustin\shared\discord\retrobot\node_modules\@discordjs\rest\src\lib\handlers\SequentialHandler.ts:99:14)
    at async REST.request (C:\Users\dustin\shared\discord\retrobot\node_modules\@discordjs\rest\src\lib\REST.ts:50:22)
    at async ButtonInteraction.update (C:\Users\dustin\shared\discord\retrobot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:225:5)
    at async C:\Users\dustin\shared\discord\retrobot\src\index.ts:155:29 {
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1020747166534340678/aW50ZXJhY3Rpb246MTAyMDc0NzE2NjUzNDM0MDY3ODpHR0NBb01pSm9EM1lLVHVOcnc4QUxDRUJUdXloOXRpQWhON3N2TzNGT2Y0SE9aMnM4M1lmb3VCaG52OFkyalhkaW1GalVhUENWU2JnZ2tKQU1zVmdXUDFQUXJwdFRScUF6bXhhMDAxOTdrcGh5RFo1Wm1oTldubE1zbWhyZW9lTA/callback',
  requestBody: { files: [], json: { type: 7, data: [Object] } }
}
```

**Comment by obezuk** [comment]
@rossimo - FYI I can consistently reproduce this in my environment
